// <auto-generated />
namespace Tydzien7Lekcja27ZD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SetFirstAndLastNameMaxLengthAndRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetFirstAndLastNameMaxLengthAndRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "202309171610263_SetFirstAndLastNameMaxLengthAndRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
